defmodule AuthBackendWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :auth_backend

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_auth_backend_key",
    signing_salt: "MrRZK8JC",
    same_site: "Lax"
  ]

  socket("/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]
  )

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug(Plug.Static,
    at: "/",
    from: :auth_backend,
    gzip: not code_reloading?,
    only: AuthBackendWeb.static_paths()
  )

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket("/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket)
    plug(Phoenix.LiveReloader)
    plug(Phoenix.CodeReloader)
    plug(Phoenix.Ecto.CheckRepoStatus, otp_app: :auth_backend)
  end

  plug(Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"
  )

  plug(Plug.RequestId)
  plug(Plug.Telemetry, event_prefix: [:phoenix, :endpoint])

  plug(Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()
  )

  plug(Plug.MethodOverride)
  plug(Plug.Head)
  plug(Plug.Session, @session_options)

  plug(RemoteIp,
    headers: ["cf-connecting-ip"],
    proxies: ~w(
    173.245.48.0/20
    103.21.244.0/22
    103.22.200.0/22
    103.31.4.0/22
    141.101.64.0/18
    108.162.192.0/18
    190.93.240.0/20
    188.114.96.0/20
    197.234.240.0/22
    198.41.128.0/17
    162.158.0.0/15
    104.16.0.0/13
    104.24.0.0/14
    172.64.0.0/13
    131.0.72.0/22
    2400:cb00::/32
    2606:4700::/32
    2803:f800::/32
    2405:b500::/32
    2405:8100::/32
    2a06:98c0::/29
    2c0f:f248::/32
  )
  )

  plug(:rate_limit)
  plug(AuthBackendWeb.Router)

  defp rate_limit(conn, _opts) do
    ip = conn.remote_ip |> :inet.ntoa() |> to_string()
    hashed_ip = :crypto.hash(:sha256, ip)
    mc_server_ip = Application.get_env(:auth_backend, :mc_server_ip)

    if :crypto.hash_equals(
         :crypto.hash(:sha256, mc_server_ip),
         hashed_ip
       ) do
      conn
    else
      hashed_ip = Base.encode16(hashed_ip)
      key = "web_requests:#{hashed_ip}"
      scale = :timer.hours(1)
      limit = 1000

      case AuthBackend.Ratelimit.hit(key, scale, limit) do
        {:allow, _count} ->
          conn

        {:deny, retry_after} ->
          retry_after_seconds = div(retry_after, 1000)

          conn
          |> put_resp_header("retry-after", Integer.to_string(retry_after_seconds))
          |> send_resp(429, [])
          |> halt()
      end
    end
  end
end
